from __future__ import annotations

import http.client
import json
import tempfile
import threading
import unittest
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlencode

from test_auth_store import make_settings

from relay_pages import store
from relay_pages.auth import Users
from relay_pages.server import Handler, make_server

FORM = {"Content-Type": "application/x-www-form-urlencoded", "Origin": "https://pages.test"}


class ServerTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.settings = make_settings(Path(self.temporary.name))
        self.settings.runtime_dir.mkdir(parents=True)
        (self.settings.runtime_dir / "bots.json").write_text(
            json.dumps({"default": {"name": "Main", "username": "main_bot"}, "2": {"name": "Two", "username": "two_bot"}})
        )
        self.users = Users(self.settings.users_path)
        self.users.set_password("owner", "correct horse battery")
        self.server = make_server(self.settings)
        self.port = self.server.server_address[1]
        self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)
        self.thread.start()
        self.meta = store.publish(
            self.settings,
            "# 私密标题\n\n机密正文 ![i](chart.png)",
            ttl_seconds=3600,
            bot={"key": "2", "name": "Two", "username": "two_bot"},
            author="Claude",
            base_dir=self._image_dir(),
        )

    def _image_dir(self) -> Path:
        directory = Path(self.temporary.name) / "img"
        directory.mkdir(exist_ok=True)
        (directory / "chart.png").write_bytes(b"\x89PNG\r\n\x1a\nimage")
        return directory

    def tearDown(self) -> None:
        self.server.shutdown()
        self.server.server_close()
        self.temporary.cleanup()

    def request(self, method: str, path: str, body: bytes | None = None, headers: dict[str, str] | None = None):
        connection = http.client.HTTPConnection("127.0.0.1", self.port, timeout=10)
        connection.request(method, path, body=body, headers=headers or {})
        response = connection.getresponse()
        data = response.read()
        connection.close()
        return response, data.decode("utf-8", errors="replace")

    def post_login(self, username: str, password: str, next_path: str = "/", headers: dict[str, str] | None = None):
        body = urlencode({"username": username, "password": password, "next": next_path}).encode()
        return self.request("POST", "/auth/login", body, {**FORM, **(headers or {})})

    def login(self, next_path: str = "/") -> str:
        response, _ = self.post_login("owner", "correct horse battery", next_path)
        self.assertEqual(response.status, 303)
        return response.getheader("Set-Cookie").split(";", 1)[0]

    def test_pages_need_a_session_and_reveal_nothing_without_one(self) -> None:
        page_id = self.meta["id"]
        response, body = self.request("GET", f"/p/{page_id}")
        self.assertEqual(response.status, 401)
        self.assertIn('<form class="rp-form" method="post" action="/auth/login">', body)
        self.assertIn('autocomplete="current-password"', body)
        self.assertNotIn("私密标题", body)
        self.assertNotIn("two_bot", body)
        _, missing = self.request("GET", "/p/aaaaaaaaaaaaaaaa")
        # Same answer whether or not the page exists (only the echoed path differs).
        self.assertEqual(body.replace(page_id, "ID"), missing.replace("aaaaaaaaaaaaaaaa", "ID"))
        self.assertEqual(self.request("GET", f"/p/{page_id}/raw")[0].status, 404)
        self.assertEqual(self.request("GET", f"/p/{page_id}/files/1.png")[0].status, 404)
        self.assertEqual(self.request("GET", "/")[0].status, 401)

    def test_password_login_sets_a_cookie_and_shows_the_page(self) -> None:
        page_id = self.meta["id"]
        response, _ = self.post_login("Owner ", "correct horse battery", f"/p/{page_id}")
        self.assertEqual((response.status, response.getheader("Location")), (303, f"/p/{page_id}"))
        cookie = response.getheader("Set-Cookie")
        for flag in ("HttpOnly", "Secure", "SameSite=Lax", "Path=/", "Max-Age=7776000"):
            self.assertIn(flag, cookie)
        cookie = cookie.split(";", 1)[0]
        page, body = self.request("GET", f"/p/{page_id}", headers={"Cookie": cookie})
        self.assertEqual(page.status, 200)
        self.assertIn('<h1 class="rp-title">私密标题</h1>', body)
        self.assertIn("机密正文", body)
        self.assertIn('href="https://t.me/two_bot"', body)
        self.assertIn('<html lang="en">', body)
        self.assertIn("<span>1 min read</span>", body)
        self.assertIn("Generated by @two_bot · Expires in 1 hour · ", body)
        self.assertIn(">Copy all</button>", body)
        raw, text = self.request("GET", f"/p/{page_id}/raw", headers={"Cookie": cookie})
        self.assertEqual((raw.status, text.splitlines()[0]), (200, "# 私密标题"))
        image, _ = self.request("GET", f"/p/{page_id}/files/1.png", headers={"Cookie": cookie})
        self.assertEqual((image.status, image.getheader("Content-Type")), (200, "image/png"))
        index, listing = self.request("GET", "/", headers={"Cookie": cookie})
        self.assertEqual(index.status, 200)
        self.assertIn(f"/p/{page_id}", listing)
        self.assertIn('action="/auth/logout"', listing)

    def test_wrong_password_and_unknown_user_look_the_same(self) -> None:
        wrong, body = self.post_login("owner", "wrong password")
        unknown, other = self.post_login("nobody", "correct horse battery")
        self.assertEqual((wrong.status, unknown.status), (401, 401))
        self.assertIn("Wrong username or password.", body)
        self.assertIn('value="owner"', body)  # the username stays filled in
        self.assertIsNone(wrong.getheader("Set-Cookie"))
        self.assertEqual(body.replace('value="owner"', ""), other.replace('value="nobody"', ""))

    def test_failed_logins_are_limited_per_address(self) -> None:
        attacker = {"X-Real-IP": "203.0.113.9"}
        for _ in range(5):
            self.assertEqual(self.post_login("owner", "guess", headers=attacker)[0].status, 401)
        limited, body = self.post_login("owner", "correct horse battery", headers=attacker)
        self.assertEqual(limited.status, 429)
        self.assertIn("Too many attempts. Try again in 15 minutes.", body)
        self.assertIsNotNone(limited.getheader("Retry-After"))
        # Another address is unaffected.
        ok, _ = self.post_login("owner", "correct horse battery", headers={"X-Real-IP": "198.51.100.4"})
        self.assertEqual(ok.status, 303)

    def test_login_rejects_foreign_origins_bad_forms_and_open_redirects(self) -> None:
        foreign, _ = self.post_login("owner", "correct horse battery", headers={"Origin": "https://evil.example"})
        self.assertEqual(foreign.status, 403)
        json_body = json.dumps({"username": "owner", "password": "correct horse battery"}).encode()
        wrong_type, _ = self.request("POST", "/auth/login", json_body, {"Content-Type": "application/json"})
        self.assertEqual(wrong_type.status, 400)
        redirect, _ = self.post_login("owner", "correct horse battery", next_path="https://evil.example/")
        self.assertEqual((redirect.status, redirect.getheader("Location")), (303, "/"))
        null_origin, _ = self.post_login("owner", "correct horse battery", headers={"Origin": "null"})
        self.assertEqual(null_origin.status, 303)

    def test_logout_and_password_change_end_the_session(self) -> None:
        cookie = self.login()
        self.assertEqual(self.request("GET", "/", headers={"Cookie": cookie})[0].status, 200)
        out, _ = self.request("POST", "/auth/logout", b"", {"Origin": "https://pages.test"})
        self.assertEqual(out.status, 303)
        self.assertIn("Max-Age=0", out.getheader("Set-Cookie"))
        self.users.set_password("owner", "a brand new password")
        self.assertEqual(self.request("GET", "/", headers={"Cookie": cookie})[0].status, 401)

    def test_expired_pages_keep_only_the_notice(self) -> None:
        cookie = self.login()
        later = store.parse_iso(self.meta["created_at"]) + timedelta(hours=2)
        store.prune(self.settings, later)
        response, body = self.request("GET", f"/p/{self.meta['id']}", headers={"Cookie": cookie})
        self.assertEqual(response.status, 410)
        self.assertIn("This page has expired.", body)
        self.assertIn("Back to chat", body)
        self.assertNotIn("机密正文", body)
        self.assertEqual(self.request("GET", f"/p/{self.meta['id']}/raw", headers={"Cookie": cookie})[0].status, 404)

    def test_security_headers_assets_and_head(self) -> None:
        response, _ = self.request("GET", f"/p/{self.meta['id']}")
        csp = response.getheader("Content-Security-Policy")
        self.assertIn("script-src 'self'", csp)
        self.assertIn("form-action 'self'", csp)
        self.assertNotIn("unsafe-inline", csp)
        self.assertEqual(response.getheader("X-Robots-Tag"), "noindex, nofollow")
        self.assertEqual(response.getheader("Cache-Control"), "private, no-store")
        self.assertEqual(response.getheader("Referrer-Policy"), "same-origin")
        css, text = self.request("GET", "/assets/relay-pages.css")
        self.assertEqual(css.status, 200)
        self.assertIn(".rp-card", text)
        self.assertEqual(self.request("GET", "/assets/../.runtime/users.json")[0].status, 404)
        head, body = self.request("HEAD", "/healthz")
        self.assertEqual((head.status, body), (200, ""))

    def test_query_strings_stay_out_of_access_logs(self) -> None:
        handler = Handler.__new__(Handler)
        handler.headers = {}
        handler.client_address = ("127.0.0.1", 1)
        with self.assertLogs("relay-pages", "INFO") as logs:
            Handler.log_message(handler, '"%s" %s', "GET /p/abc?theme=dark&secret=1 HTTP/1.1", "200")
        self.assertNotIn("secret", logs.output[0])
        self.assertIn("/p/abc", logs.output[0])


if __name__ == "__main__":
    unittest.main()
